version: "3"
services:
  backend:
    build: .
    image: mailer-backend:latest
    container_name: mailer-backend
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    command: python app/main.py
